name: Wicked Awesome Reviews
favicon: null
layout_spectrum: 0.5421682565938681
typography_spectrum: 0.9381149352993816
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.24161962047219276
  lightness: 0.15845384844578803
  saturation: 0.374256937764585
  rhythmicContrast: 0.7568172311875969
purpose: []
