name: Wicked Awesome Reviews
favicon: null
layout_spectrum: 0.2531
typography_spectrum: 0.9381149352993816
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fac08f'
    - '#bb2023'
    - '#006b50'
    - '#000000'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
